version: '3.8'

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 10s
      retries: 5
      start_period: 10s

  backend:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: ./ETL
      dockerfile: Dockerfile
    volumes:
      - ./ETL:/app/ETL
    environment:
      DATABASE_URL: postgresql://user:password@postgres/mydatabase
    networks:
      - mynetwork
    command: python /app/ETL/Main.py  # Ajuste do caminho

  frontend:
    build:
      context: ./dataviz
      dockerfile: Dockerfile  # Ajuste para seguir convenção
    volumes:
      - ./dataviz:/dataviz
    ports:
      - "8501:8501"
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
